apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meu-ingress
spec:
  rules:
    - host: minha-aplicacao.local
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: meu-service-clusterip
                port:
                  number: 80
    - host: nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: servico-nginx
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: meu-service-clusterip
spec:
  selector:
    app: minha-aplicacao
  ports:
    - protocol: TCP
      port: 80  # Porta do serviço
      targetPort: 8080  # Porta do pod
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: servico-nginx
  namespace: natacosta
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: app
   namespace: natancosta
spec:
  selector:
    matchLabels:
       app: nginx
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx

---

apiVersion: v1
kind: Namespace
metadata:
  name: natancosta
